### create visitors
POST http://localhost:4000/register-staff
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF6YSIsInJvbGUiOiJzZWN1cml0eSIsImlhdCI6MTcwMzQ3OTM1N30.E-jqj8nUF4Uxj_qUvysJBBXgzjrfilACmRqGdis8vGg

{
  "username": "azizah",
  "password": "321" 
}
// staff registration

###

POST http://localhost:4000/register-security
Content-Type: application/json

{
  "username": "bob",
  "password": "123" 
}
// security registration

###

POST http://localhost:4000/login-staff
Content-Type: application/json

{
  "username": "azizah",
  "password": "321" 
}
// staff login

###

POST http://localhost:4000/login-security
Content-Type: application/json

{
  "username": "aza",
  "password": "123" 
}
// security login

###

POST http://localhost:4000/appointments
Content-Type: application/json

{
  "name": "yat",
  "company": "ABC Corporation",
  "purpose": "meeting",
  "phoneNo": "011223344",
  "date": "26-6-2023",
  "time": "12:00AM",
  "verification": "N/A",
  "staff": {
    "username": "fadh"
  }
}

###

GET http://localhost:4000/staff-appointments/aza
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF6YSIsInJvbGUiOiJzZWN1cml0eSIsImlhdCI6MTcwMzQ3OTM1N30.E-jqj8nUF4Uxj_qUvysJBBXgzjrfilACmRqGdis8vGg

###

PUT http://localhost:4000/appointments/yat
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJyb2xlIjoic3RhZmYiLCJpYXQiOjE2ODgwMzUzMjR9.6wI_N4QpTqY-eixW3rzOsNew76vvlbPL3a2weZRcYsk
Content-Type: application/json

{ "verification": "verified" }

###

DELETE http://localhost:4000/appointments/yat
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZhZGgiLCJyb2xlIjoic3RhZmYiLCJpYXQiOjE2ODc2ODM1NDh9.XkbTmIIEl9YSoZfuEJJCuhwDln_PU9pLrOktBOdVsok

####

GET http://localhost:4000/appointments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF6YSIsInJvbGUiOiJzZWN1cml0eSIsImlhdCI6MTcwMzQ3OTM1N30.E-jqj8nUF4Uxj_qUvysJBBXgzjrfilACmRqGdis8vGg

//optional
###
POST http://localhost:4000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZhZGgiLCJyb2xlIjoic3RhZmYiLCJpYXQiOjE2ODc3MDc4NTR9.7SH9XF5k48Zp4w0OQONs6nA0Enf0Rl1FMAb0DZD2fsU
Content-Type: application/json

{
  "username": "fadh"
}